"""update foregnkey property

Revision ID: 1c7555eff29c
Revises: a6458d5143b0
Create Date: 2023-02-22 15:24:59.257747

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c7555eff29c"
down_revision = "a6458d5143b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "assignment_related_session_fkey", "assignment", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "assignment",
        "training_session",
        ["related_session"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("grade_assignment_fk_fkey", "grade", type_="foreignkey")
    op.drop_constraint("grade_user_fk_fkey", "grade", type_="foreignkey")
    op.create_foreign_key(
        None, "grade", "users", ["user_fk"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "grade", "assignment", ["assignment_fk"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        "grade_pattern_grade_fk_fkey", "grade_pattern", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "grade_pattern", "grade", ["grade_fk"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        "session_attendee_session_id_fkey", "session_attendee", type_="foreignkey"
    )
    op.drop_constraint(
        "session_attendee_user_id_fkey", "session_attendee", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "session_attendee",
        "training_session",
        ["session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "session_attendee", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        "training_session_user_fk_fkey", "training_session", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "training_session", "users", ["user_fk"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "training_session", type_="foreignkey")
    op.create_foreign_key(
        "training_session_user_fk_fkey",
        "training_session",
        "users",
        ["user_fk"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "session_attendee", type_="foreignkey")
    op.drop_constraint(None, "session_attendee", type_="foreignkey")
    op.create_foreign_key(
        "session_attendee_user_id_fkey",
        "session_attendee",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "session_attendee_session_id_fkey",
        "session_attendee",
        "training_session",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "grade_pattern", type_="foreignkey")
    op.create_foreign_key(
        "grade_pattern_grade_fk_fkey",
        "grade_pattern",
        "grade",
        ["grade_fk"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "grade", type_="foreignkey")
    op.drop_constraint(None, "grade", type_="foreignkey")
    op.create_foreign_key(
        "grade_user_fk_fkey", "grade", "users", ["user_fk"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "grade_assignment_fk_fkey",
        "grade",
        "assignment",
        ["assignment_fk"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "assignment", type_="foreignkey")
    op.create_foreign_key(
        "assignment_related_session_fkey",
        "assignment",
        "training_session",
        ["related_session"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
