"""update fk relational name

Revision ID: 1dac60e45bb3
Revises: 4abc10fdef81
Create Date: 2023-02-27 23:39:58.968244

"""

# revision identifiers, used by Alembic.
revision = "1dac60e45bb3"
down_revision = "4abc10fdef81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
