"""rename model from Grade to Submission

Revision ID: 2eab7ff80918
Revises: 37d78a7a50cb
Create Date: 2023-02-24 19:33:54.953119

"""

# revision identifiers, used by Alembic.
revision = "2eab7ff80918"
down_revision = "37d78a7a50cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
