"""update grade model

Revision ID: 37d78a7a50cb
Revises: 1c7555eff29c
Create Date: 2023-02-24 18:36:14.467039

"""
# revision identifiers, used by Alembic.
revision = "37d78a7a50cb"
down_revision = "1c7555eff29c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
