"""set  uselist=False for submission grade

Revision ID: 672186f61222
Revises: 1dac60e45bb3
Create Date: 2023-02-27 23:52:18.628768

"""

# revision identifiers, used by Alembic.
revision = "672186f61222"
down_revision = "1dac60e45bb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
