"""update training session time type

Revision ID: 81b8cddd7d4e
Revises: da66ebf96334
Create Date: 2023-02-22 12:39:50.386232

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "81b8cddd7d4e"
down_revision = "da66ebf96334"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_session", "session_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_session",
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
