"""update submission detail

Revision ID: a6d257f8298c
Revises: d69f3ce1588b
Create Date: 2023-02-21 15:52:12.392224

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a6d257f8298c"
down_revision = "d69f3ce1588b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grade", sa.Column("submission_detail", sa.String(), nullable=True))
    op.add_column("grade", sa.Column("submission_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grade", "submission_date")
    op.drop_column("grade", "submission_detail")
    # ### end Alembic commands ###
