"""update field name in training_session

Revision ID: d69f3ce1588b
Revises: 117a1a877ad3
Create Date: 2023-02-21 12:53:26.953519

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d69f3ce1588b"
down_revision = "117a1a877ad3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_session", sa.Column("session_date", sa.Date(), nullable=True)
    )
    op.drop_column("training_session", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_session",
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.drop_column("training_session", "session_date")
    # ### end Alembic commands ###
