"""update training session time type

Revision ID: da66ebf96334
Revises: a6d257f8298c
Create Date: 2023-02-22 11:37:49.750462

"""

# revision identifiers, used by Alembic.
revision = "da66ebf96334"
down_revision = "a6d257f8298c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
